AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 128
    Timeout: 3
    Tracing: Active

Resources:
  ResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Ref: AWS::StackName
  GinFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Runtime: go1.x
      Handler: main
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /gin/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: makefile
  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Runtime: go1.x
      Handler: main
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /echo/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: makefile
  PythonCommonLayerA:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/python-common-a
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
  PythonCommonLayerB:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile
  PythonInlineFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      Layers:
        - Ref: PythonCommonLayerA
        - Ref: PythonCommonLayerB
      InlineCode: |
        import common_a
        import common_b
        def handler(event, context):
          # call common_a layer
          print(common_a.say_hello())
          print(common_a.call_echo())
          # call common_b layer
          print(common_b.say_hello())
  NodejsCommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/nodejs-common
      CompatibleRuntimes:
        - nodejs16.x
    Metadata:
      BuildMethod: nodejs16.x
  NodejsInlineFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      Layers:
        - Ref: NodejsCommonLayer
      Environment:
        Variables:
          DEBUG: "*"
      InlineCode: |
        const debug = require('debug')('lambda')
        module.exports = {
          async handler(event) {
            debug(JSON.stringify(event, null, 2))
          }
        }

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  PythonFunctionArn:
    Value: !GetAtt PythonInlineFunction.Arn
  NodejsFunctionArn:
    Value: !GetAtt NodejsInlineFunction.Arn
